apiVersion: apps/v1
kind: Deployment
metadata:
  name: assist-genie-orch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assist-genie-orch
  template:
    metadata:
      labels:
        app: assist-genie-orch
    spec:
      serviceAccountName: assistgenie-serviceaccount
      containers:
        - name: assist-genie-orch
          image: europe-west2-docker.pkg.dev/playpen-5bf1e3/main/assist-genie:0.5
          env:
            - name: AGENTIC_SERVICE_URL
              value: http://34.39.49.223:3000
            ports:
              containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: assist-genie-orch
spec:
  selector:
    app: assist-genie-arch
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: Load Balancer

